### ISSUE TITLE
Stripping HTTPS from Invalid URL

### ISSUE THREAD

**Issue by james-crowley** [AdoptOpenJDK/openjdk-api-v3#166]
While playing around with the API, I made a invalid request to:

```
https://api.adoptopenjdk.net/v3/binary/jdk-14+36/linux/s390x/jdk/hotspot/normal/adoptopenjdk?project=jdk
```

The error message is slightly messed up:

```
RESTEASY003210: Could not find resource for full path: http://api.adoptopenjdk.net/v3/binary/jdk-14+36/linux/s390x/jdk/hotspot/normal/adoptopenjdk?project=jdk
```

Even though the invalid request was to a `HTTPS` link, the error message states that the request is to a `HTTP` link.

**Comment by nickebbitt** [comment]
I suppose this is happening because TLS is being terminated before the request reaches the API?

Thinking about the solutiuon, maybe it's worth actually suppressing the response body completely? The HTTP 404 response provides enough information in its own right i.e. the resource requested could not be found.

This would avoid the reported issue as well as prevent internal implementation details (e.g. RESTEASY) being leaked via the API.
