### ISSUE TITLE
Possibly(?) incorrect parsing in ​/v3​/version​/{version}

### ISSUE THREAD

**Issue by tushev** [AdoptOpenJDK/openjdk-api-v3#366]
**Describe the bug**
While testing the version parser in the API, I noticed an unusual response, like `"semver": "11.0.9+111.1"`.

**To Reproduce**
1. Go to **​/v3​/version​/{version}**: https://api.adoptopenjdk.net/swagger-ui/#/Version/get_v3_version__version_
2. Enter `11.0.9.1+11.1` in Version, hit **Execute**
3. Receive the JSON:
```
{
  "adopt_build_number": 1,
  "build": 11,
  "major": 11,
  "minor": 0,
  "openjdk_version": "11.0.9.1+11.1",
  "patch": 1,
  "security": 9,
  "semver": "11.0.9+111.1"
}
```

**Expected behavior**
I am not sure that `"semver": "11.0.9+111.1"` is a valid response. Please confirm or refute this.

_Definitely not a critical/blocking issue, just noticed this and letting you know..._

**Comment by johnoliver** [comment]
This is a result of the issue we had where Java versions cannot be represented fully in semver due to semver being limited to 3 version numbers, that resulted in the `(100*b)+x` format you noted at https://github.com/AdoptOpenJDK/openjdk-build/issues/2248#issuecomment-732980755 unfortunately I think the only long term solution is to not use semver if/when we move to v4 api, until then I think we will be parsing in this way.
